# En plan som säger vart Spring Boot ska försöka ansluta!
spring.application.name=bookingsystemAPI
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/bookingsdb
spring.datasource.username=postgres
spring.datasource.password=password123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect